### ISSUE TITLE
Graceful failure when not finding certs

### ISSUE THREAD

**Issue by patriotyk** [uNetworking/uWebSockets#1016]
I get segfauts when run examples wich uses `uWS::SSLApp` and when library is compiled with ssl support. I tried all version starting from v0.16.6.
I  get the following stacktrace:
```
gdb ./EchoServer
GNU gdb (Ubuntu 9.1-0ubuntu1) 9.1
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./EchoServer...
(gdb) r
Starting program: /media/data/project/somefolder/projectname/libs/uWebSockets/EchoServer 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
0x000055555556d48b in us_internal_create_child_ssl_socket_context (context=0x0, context_ext_size=768) at src/crypto/wolfssl.c:309
309         struct us_internal_ssl_socket_context_t *child_context = (struct us_internal_ssl_socket_context_t *) us_create_socket_context(0, context->sc.loop, sizeof(struct us_internal_ssl_socket_context_t) + context_ext_size, options);
(gdb) where
#0  0x000055555556d48b in us_internal_create_child_ssl_socket_context (context=0x0, context_ext_size=768) at src/crypto/wolfssl.c:309
#1  0x000055555556bec5 in us_create_child_socket_context (ssl=<optimized out>, context=<optimized out>, context_ext_size=<optimized out>)
    at src/context.c:199
#2  0x000055555555a036 in uWS::WebSocketContext<true, true>::create (parentSocketContext=0x0, loop=<optimized out>) at src/WebSocketContext.h:374
#3  uWS::TemplatedApp<true>::ws<main()::PerSocketData> (behavior=..., pattern="", this=0x7fffffffd800) at src/App.h:106
#4  main () at examples/EchoServer.cpp:45

```

**Comment by SlavSlavov** [comment]
This usually happens when you forget to add certificates or the path is wrong.

**Comment by patriotyk** [comment]
Oh, thank you!!! You are right, now it works.
But why not to include certificates and point to them in the examples?

**Comment by alexhultman-2fa** [comment]
This flaw could be handled a lot prettier, indeed. Will have a look at it

**Comment by alexhultman** [comment]
Thanks for reporting. Latest master will now report this kind of issue by failing to listen - you cannot listen if SSL cert/key was missing. It fails as if it couldn't listen to the port.
