### ISSUE TITLE
Segfault when starting/stopping web server repeatedly on thread

### ISSUE THREAD

**Issue by cbecker** [uNetworking/uWebSockets#1420]
Hello. First thanks for making this library public, it's handy to have such clean lib API to code web services.

I think I found a bug that appears when constructing/destroying repeatedly an application. This is a minimal example that triggers a segfault. I tried this with 20.10.0, I couldn't try with 20.11.0 yet because I have an old gcc at the moment and won't compile the newest version due to a missing header/libcpp.

```cpp
#include <uWebSockets/App.h>
#include <future>
#include <gmock/gmock.h>
#include <gtest/gtest.h>
#include <curl/curl.h>

enum class WebServerStatus { NOT_STARTED, STARTED, ERROR_LISTENING };

// class to run web server in separate thread
class WebServer
{
public:
    WebServer(uint16_t port) : m_status(WebServerStatus::NOT_STARTED), m_port(port) {}

    ~WebServer()
    {
        {
            std::scoped_lock lock(m_mutex);
            if (m_listeningSocket) { us_listen_socket_close(0, *m_listeningSocket); }
        }

        if (m_threadRunning.valid()) { m_threadRunning.wait(); }
    }

    void runInSeparateThread()
    {
        m_threadRunning = std::async(std::launch::async, [obj = this]() {
            uWS::App()
                .get("/metrics", [](uWS::HttpResponse<false>* response,
                                    uWS::HttpRequest* /*request*/) { response->end("bye"); })
                .listen(obj->m_port, LIBUS_LISTEN_EXCLUSIVE_PORT /* single thread, don't allow
                                                                      multiple
                                                                      instances per
                                                                      port */
                        ,
                        [&obj](auto* socket) {
                            std::scoped_lock lock(obj->m_mutex);
                            if (socket)
                            {
                                obj->m_listeningSocket.emplace(socket);
                                obj->m_status = WebServerStatus::STARTED;
                            }
                            else
                            {
                                obj->m_status = WebServerStatus::ERROR_LISTENING;
                            }
                        })
                .run();
            return true;
        });
    }

    [[nodiscard]] WebServerStatus status() const { return m_status; }

    // use a std::future to hold whether the thread is running to avoid synchronization issues or
    // mutexes
    std::future<bool> m_threadRunning;

    std::mutex m_mutex;
    WebServerStatus m_status;
    std::optional<us_listen_socket_t*> m_listeningSocket;

    const uint16_t m_port;
};

TEST(myWebServer, runs)
{
    WebServer webServer(5559);
    webServer.runInSeparateThread();
    while (webServer.m_status != WebServerStatus::STARTED)
    { std::this_thread::sleep_for(std::chrono::milliseconds(1)); }

    auto curlHandle = curl_easy_init();
    curl_easy_setopt(curlHandle, CURLOPT_URL, "http://localhost:5559/metrics");
    curl_easy_perform(curlHandle);
    curl_easy_cleanup(curlHandle);
}
```

It requires gtest and curl, apart from uWebSockets. When running with `--gtest_repeat=-1`, after a few iterations I get the following error:

```
Repeating all tests (iteration 5) . . .

Note: Google Test filter = *runs
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from myWebServer
[ RUN      ] myWebServer.runs
[New Thread 0x7ffff5b5d700 (LWP 118321)]

Thread 6 "tests_unit_comm" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff5b5d700 (LWP 118321)]
_int_malloc (av=av@entry=0x7ffff0000020, bytes=bytes@entry=8) at malloc.c:4038
4038    malloc.c: No such file or directory.
(gdb) bt
#0  _int_malloc (av=av@entry=0x7ffff0000020, bytes=bytes@entry=8) at malloc.c:4038
#1  0x00007ffff63b43cd in __GI___libc_malloc (bytes=8) at malloc.c:3075
#2  0x00007ffff6d6cc78 in operator new(unsigned long) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x000055555558a30a in __gnu_cxx::new_allocator<std::unique_ptr<uWS::HttpRouter<uWS::HttpContextData<false>::RouterData>::Node, std::default_delete<uWS::HttpRouter<uWS::HttpContextData<false>::RouterData>::Node> > >::allocate (
    this=<optimized out>, __n=<optimized out>) at /usr/include/c++/7/ext/new_allocator.h:111
#4  std::allocator_traits<std::allocator<std::unique_ptr<uWS::HttpRouter<uWS::HttpContextData<false>::RouterData>::Node, std::default_delete<uWS::HttpRouter<uWS::HttpContextData<false>::RouterData>::Node> > > >::allocate (__a=..., 
    __n=<optimized out>) at /usr/include/c++/7/bits/alloc_traits.h:436
#5  std::_Vector_base<std::unique_ptr<uWS::HttpRouter<uWS::HttpContextData<false>::RouterData>::Node, std::default_delete<uWS::HttpRouter<uWS::HttpContextData<false>::RouterData>::Node> >, std::allocator<std::unique_ptr<uWS::HttpRouter<uWS::HttpContextData<false>::RouterData>::Node, std::default_delete<uWS::HttpRouter<uWS::HttpContextData<false>::RouterData>::Node> > > >::_M_allocate (this=<optimized out>, __n=<optimized out>) at /usr/include/c++/7/bits/stl_vector.h:172
#6  std::vector<std::unique_ptr<uWS::HttpRouter<uWS::HttpContextData<false>::RouterData>::Node, std::default_delete<uWS::HttpRouter<uWS::HttpContextData<false>::RouterData>::Node> >, std::allocator<std::unique_ptr<uWS::HttpRouter<uWS::HttpContextData<false>::RouterData>::Node, std::default_delete<uWS::HttpRouter<uWS::HttpContextData<false>::RouterData>::Node> > > >::_M_realloc_insert<std::unique_ptr<uWS::HttpRouter<uWS::HttpContextData<false>::RouterData>::Node, std::default_delete<uWS::HttpRouter<uWS::HttpContextData<false>::RouterData>::Node> > > (this=0x7ffff00055b0, __position=<error reading variable: Cannot access memory at address 0x8009f0006238>, 
    __position@entry=non-dereferenceable iterator for std::vector) at /usr/include/c++/7/bits/vector.tcc:406
#7  0x000055555558a72f in std::vector<std::unique_ptr<uWS::HttpRouter<uWS::HttpContextData<false>::RouterData>::Node, std::default_delete<uWS::HttpRouter<uWS::HttpContextData<false>::RouterData>::Node> >, std::allocator<std::unique_ptr<uWS::HttpRouter<uWS::HttpContextData<false>::RouterData>::Node, std::default_delete<uWS::HttpRouter<uWS::HttpContextData<false>::RouterData>::Node> > > >::_M_insert_rval (this=this@entry=0x7ffff00055b0, __position=..., __v=...)
    at /usr/include/c++/7/bits/vector.tcc:327

```
(The backtrace continues)

Is there something I am doing wrong about how to use uWS::App()? I want to have a separate thread running it and be able to stop it when the respective object is destroyed. Thanks!

**Comment by cbecker** [comment]
I am closing this as I am seeing some inconsistencies in my testing, it may only happen with certain flags/compiled, I will re-open if I have new info, sorry for the potential false alarm.
