### ISSUE TITLE
Getting segmentation fault , need help.

### ISSUE THREAD

**Issue by ReddyArunreddy** [uNetworking/uWebSockets#1453]
compiled  below code but while running getting segmentation fault at ).get("/LI_REQUEST", [](auto *res, auto *req)

thanks.

#include <App.h>
/* Helpers for this example */
//#include "helpers/AsyncFileReader.h"
//#include "helpers/AsyncFileStreamer.h"
//#include "helpers/Middleware.h"

/* optparse */
#define OPTPARSE_IMPLEMENTATION
#include "helpers/optparse.h"
using namespace std;

int main(int argc, char **argv) {

 auto app=uWS::SSLApp({ .key_file_name="./privkey1.pem",
.cert_file_name="./cert1.pem"
}
).get("/LI_REQUEST", [](auto *res, auto *req)
        {
         res->writeHeader("Content-Type", "text/html; charset=utf-8")->end("Hello HTTP!");
        }).post("/LI_REQUEST", [](auto *res, auto *req)
        {
          res->end("Hello world!");
        }).listen("10.63.89.199",6080, [port](auto *token)
        {
            if (token)
            {
                          printf("RtLIHttpHandler() :: LISTENING ON port-1\n");
                std::cout << "Listening on port " << port << std::endl;
            }
        }).run();

  std::cout << "Failed to listen to port " << port << std::endl;
}

Error msg:
==3268318==The signal is caused by a READ memory access.
==3268318==Hint: address points to the zero page.
    #0 0x4287f3 in uWS::HttpRouter<uWS::HttpContextData<true>::RouterData>::add(std::string, std::basic_string_view<char, std::char_traits<char> >, fu2::abi_400::detail::function<fu2::abi_400::detail::config<true, false, fu2::capacity_default>, fu2::abi_400::detail::property<true, false, bool (uWS::HttpContextData<true>::RouterData&, std::pair<int, std::basic_string_view<char, std::char_traits<char> >*>)> >&&) src/HttpRouter.h:225
    #1 0x42af25 in uWS::HttpContext<true>::onHttp(std::string, std::string, fu2::abi_400::detail::function<fu2::abi_400::detail::config<true, false, fu2::capacity_default>, fu2::abi_400::detail::property<true, false, void (uWS::HttpResponse<true>*, uWS::HttpRequest*)> >&&) src/HttpContext.h:347
    #2 0x42af25 in uWS::TemplatedApp<true>::get(std::string, fu2::abi_400::detail::function<fu2::abi_400::detail::config<true, false, fu2::capacity_default>, fu2::abi_400::detail::property<true, false, void (uWS::HttpResponse<true>*, uWS::HttpRequest*)> >&&) src/App.h:231
    #3 0x404649 in main examples/HttpServer.cpp:17
    #4 0x7f2d5de8f492 in __libc_start_main (/lib64/libc.so.6+0x23492)
    #5 0x40584d in _start (ssl_test/uWebSockets-0.16.0b1/HttpServer+0x40584d)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV src/HttpRouter.h:225 in uWS::HttpRouter<uWS::HttpContextData<true>::RouterData>::add(std::string, std::basic_string_view<char, std::char_traits<char> >, fu2::abi_400::detail::function<fu2::abi_400::detail::config<true, false, fu2::capacity_default>, fu2::abi_400::detail::property<true, false, bool (uWS::HttpContextData<true>::RouterData&, std::pair<int, std::basic_string_view<char, std::char_traits<char> >*>)> >&&)

**Comment by ReddyArunreddy** [comment]
resolved

**Comment by ReddyArunreddy** [comment]
closed
