### ISSUE TITLE
After upgrading to v20.46.0 unable to run on NodeJS v20.11.1

### ISSUE THREAD

**Issue by sailingwithsandeep** [uNetworking/uWebSockets#1770]
[1]  Error: This version of uWS.js supports only Node.js LTS versions 16, 18 and 20 on (glibc) Linux, macOS and Windows, on Tier 1 platforms (https://github.com/nodejs/node/blob/master/BUILDING.md#platform-list).

```
 Error: dlopen(/Users/userx/Projects/backend/node_modules/uWebSockets.js/uws_darwin_arm64_115.node, 0x0001): symbol not found in flat namespace '_lsquic_conn_get_ctx'
   at /Users/userx/Projects/backend/node_modules/uWebSockets.js/uws.js:22:9
 at Object.<anonymous> (/Users/userx/Projects/backend/node_modules/uWebSockets.js/uws.js:24:3)
     at Module._compile (node:internal/modules/cjs/loader:1376:14)
   at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
   at Module._load (node:internal/modules/cjs/loader:1023:12)
   at cjsLoader (node:internal/modules/esm/translators:356:17)
     at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:305:7)
     at ModuleJob.run (node:internal/modules/esm/module_job:218:25)
     at async ModuleLoader.import (node:internal/modules/esm/loader:329:24)
```

**Comment by uNetworkingAB** [comment]
Ah ok, the migration to macOS 12 broke ARM64 macOS even more than before. Thanks for reporting, it should only affect macOS for ARM64

**Comment by sailingwithsandeep** [comment]
Sorry, posting in parent repo

**Comment by sailingwithsandeep** [comment]
> Ah ok, the migration to macOS 12 broke ARM64 macOS even more than before. Thanks for reporting, it should only affect macOS for ARM64

Any workaround?
