### ISSUE TITLE
Properly destruct everything on App destructor

### ISSUE THREAD

**Issue by alexhultman** [uNetworking/uWebSockets#803]
Some memory leaks are left, needs fixing. Should exit gracefully with no ASAN leaks after Autobahn and tons of various testing.

App destructor should clean everything up, except for some things attached to the Loop which should destruct in Loop destructor

**Comment by alexhultman** [comment]
Autobahn leaves one leak in both SSL and non-SSL:

SSL:
```
=================================================================
==15622==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 31 byte(s) in 1 object(s) allocated from:
    #0 0x7ff831b1a458 in operator new(unsigned long) (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xe0458)
    #1 0x559037e8228c in __gnu_cxx::new_allocator<char>::allocate(unsigned long, void const*) /usr/include/c++/7/ext/new_allocator.h:111
    #2 0x559037e7b096 in std::allocator_traits<std::allocator<char> >::allocate(std::allocator<char>&, unsigned long) /usr/include/c++/7/bits/alloc_traits.h:436
    #3 0x559037e74c7a in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_create(unsigned long&, unsigned long) /usr/include/c++/7/bits/basic_string.tcc:153
    #4 0x559037e7a996 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_mutate(unsigned long, unsigned long, char const*, unsigned long) /usr/include/c++/7/bits/basic_string.tcc:317
    #5 0x559037e748dc in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_append(char const*, unsigned long) /usr/include/c++/7/bits/basic_string.tcc:370
    #6 0x559037e70484 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::append(char const*, unsigned long) /usr/include/c++/7/bits/basic_string.h:1235
    #7 0x559037e78b75 in uWS::AsyncSocket<true>::write(char const*, int, bool, int) ../src/AsyncSocket.h:179
    #8 0x559037e80965 in uWS::AsyncSocket<true>::uncork(char const*, int, bool) ../src/AsyncSocket.h:202
    #9 0x559037e80f75 in _ZZN3uWS16WebSocketContextILb1ELb1EE4initEvENKUlPT_PciE0_clI13us_ssl_socketEEDaS3_S4_i ../src/WebSocketContext.h:264
    #10 0x559037e8e064 in _ZZN3uWS16WebSocketContextILb1ELb1EE4initEvENUlPT_PciE0_4_FUNI13us_ssl_socketEEDTcldtdeLPv0EonclscOS3_fp_scOS4_fp0_scOifp1_EES3_S4_i ../src/WebSocketContext.h:250
    #11 0x559037ea6972 in ssl_on_data ../uSockets/src/ssl.c:219
    #12 0x559037ea7a65 in us_internal_dispatch_ready_poll ../uSockets/src/loop.c:218
    #13 0x559037ea4f88 in us_loop_run ../uSockets/src/eventing/epoll.c:49
    #14 0x559037e6c111 in uWS::Loop::run() ../src/Loop.h:133
    #15 0x559037e6c125 in uWS::run() ../src/Loop.h:145
    #16 0x559037e740ae in uWS::TemplatedApp<true>::run() ../src/App.h:256
    #17 0x559037e64fcb in main ../misc/main.cpp:68
    #18 0x7ff8305abb96 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b96)

SUMMARY: AddressSanitizer: 31 byte(s) leaked in 1 allocation(s).
```

non-SSL:
```
=================================================================
==21981==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 31 byte(s) in 1 object(s) allocated from:
    #0 0x7fe028b0b458 in operator new(unsigned long) (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xe0458)
    #1 0x55d145794ee6 in __gnu_cxx::new_allocator<char>::allocate(unsigned long, void const*) /usr/include/c++/7/ext/new_allocator.h:111
    #2 0x55d14578de4c in std::allocator_traits<std::allocator<char> >::allocate(std::allocator<char>&, unsigned long) /usr/include/c++/7/bits/alloc_traits.h:436
    #3 0x55d145787c7a in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_create(unsigned long&, unsigned long) /usr/include/c++/7/bits/basic_string.tcc:153
    #4 0x55d14578d74c in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_mutate(unsigned long, unsigned long, char const*, unsigned long) /usr/include/c++/7/bits/basic_string.tcc:317
    #5 0x55d1457878dc in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_append(char const*, unsigned long) /usr/include/c++/7/bits/basic_string.tcc:370
    #6 0x55d145783484 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::append(char const*, unsigned long) /usr/include/c++/7/bits/basic_string.h:1235
    #7 0x55d14578b8a2 in uWS::AsyncSocket<false>::write(char const*, int, bool, int) ../src/AsyncSocket.h:179
    #8 0x55d1457936e3 in uWS::AsyncSocket<false>::uncork(char const*, int, bool) ../src/AsyncSocket.h:202
    #9 0x55d145793bcf in _ZZN3uWS16WebSocketContextILb0ELb1EE4initEvENKUlPT_PciE0_clI9us_socketEEDaS3_S4_i ../src/WebSocketContext.h:264
    #10 0x55d1457a0cb0 in _ZZN3uWS16WebSocketContextILb0ELb1EE4initEvENUlPT_PciE0_4_FUNI9us_socketEEDTcldtdeLPv0EonclscOS3_fp_scOS4_fp0_scOifp1_EES3_S4_i ../src/WebSocketContext.h:250
    #11 0x55d1457ba6b1 in us_internal_dispatch_ready_poll ../uSockets/src/loop.c:218
    #12 0x55d1457b7bd4 in us_loop_run ../uSockets/src/eventing/epoll.c:49
    #13 0x55d14577f111 in uWS::Loop::run() ../src/Loop.h:133
    #14 0x55d14577f125 in uWS::run() ../src/Loop.h:145
    #15 0x55d1457870ae in uWS::TemplatedApp<false>::run() ../src/App.h:256
    #16 0x55d145777fcb in main ../misc/main.cpp:68
    #17 0x7fe02759cb96 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b96)

SUMMARY: AddressSanitizer: 31 byte(s) leaked in 1 allocation(s).
```

**Comment by alexhultman** [comment]
Triggered by test 5.15, something wrong with uncorking websockets

**Comment by alexhultman** [comment]
This is a bug in the corking logic of AsyncSocket. If uncorking a closed socket, it should not try and send anything but simply reset the cork buffer. This makes it pass entire Autobahn with no leaks and clean exit.

**Comment by alexhultman** [comment]
Seems to be completely fixed for now
