### ISSUE TITLE
 This version of µWS is not compatible with your Node.js build

### ISSUE THREAD

**Issue by car1ot** [uNetworking/uWebSockets#993]
Node.js build:\n\n' + e.toString());
                ^

Error: This version of µWS is not compatible with your Node.js build:

Error: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by /root/backend/node_modules/uWebSockets.js/uws_linux_x64_72.node)
    at /root/backend/node_modules/uWebSockets.js/uws.js:29:9
    at Object.<anonymous> (/root/backend/node_modules/uWebSockets.js/uws.js:31:3)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/root/backend/index.js:1:13)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by car1ot** [comment]
I'm using: CentOS-7-amd64

**Comment by alexhultman** [comment]
![](https://66.media.tumblr.com/tumblr_lls3jjwZu11qkae66o1_1280.jpg)

**Comment by car1ot** [comment]
@alexhultman ?
